name: ci
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - "*.md"
  pull_request:
    branches:
      - master

jobs:
  get-git-ref:
    name: Get Git Ref
    runs-on: ubuntu-latest
    outputs:
      ref: ${{steps.get-git-ref.outputs.ref}}
    steps:
      - name: Checkout Repo
        run: echo "::set-output name=ref::${{ github.ref }}"
  alpine:
    needs: get-git-ref
    name: Alpine Linux
    uses: actionstoolbox/container-framework-actions/.github/workflows/multiple-os-workflow.yml@master
    with:
      directory: alpine
      ref: ${{ needs.get-git-ref.outputs.ref }}
  amazonlinux:
    needs: get-git-ref
    name: Amazon Linux
    uses: actionstoolbox/container-framework-actions/.github/workflows/multiple-os-workflow.yml@master
    with:
      directory: amazonlinux
      ref: ${{ needs.get-git-ref.outputs.ref }}
  archlinux:
    needs: get-git-ref
    name: Arch Linux
    uses: actionstoolbox/container-framework-actions/.github/workflows/multiple-os-workflow.yml@master
    with:
      directory: archlinux
      ref: ${{ needs.get-git-ref.outputs.ref }}
  centos:
    needs: get-git-ref
    name: Centos
    uses: actionstoolbox/container-framework-actions/.github/workflows/multiple-os-workflow.yml@master
    with:
      directory: centos
      ref: ${{ needs.get-git-ref.outputs.ref }}
  debian:
    needs: get-git-ref
    name: Debian
    uses: actionstoolbox/container-framework-actions/.github/workflows/multiple-os-workflow.yml@master
    with:
      directory: debian
      ref: ${{ needs.get-git-ref.outputs.ref }}
  oraclelinux:
    needs: get-git-ref
    name: Oracle Linux
    uses: actionstoolbox/container-framework-actions/.github/workflows/multiple-os-workflow.yml@master
    with:
      directory: oraclelinux
      ref: ${{ needs.get-git-ref.outputs.ref }}
  photon:
    needs: get-git-ref
    name: Photon
    uses: actionstoolbox/container-framework-actions/.github/workflows/multiple-os-workflow.yml@master
    with:
      directory: photon
      ref: ${{ needs.get-git-ref.outputs.ref }}
  scientificlinux:
    needs: get-git-ref
    name: Ccientific Linux
    uses: actionstoolbox/container-framework-actions/.github/workflows/multiple-os-workflow.yml@master
    with:
      directory: scientificlinux
      ref: ${{ needs.get-git-ref.outputs.ref }}
  ubuntu:
    needs: get-git-ref
    name: Photon
    uses: actionstoolbox/container-framework-actions/.github/workflows/multiple-os-workflow.yml@master
    with:
      directory: ubuntu
      ref: ${{ needs.get-git-ref.outputs.ref }}
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Shellcheck
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/shellcheck/master/pipeline.sh)
  slack-workflow-status:
    if: always()
    name: Slack Post Workflow Notification
    needs:
      - alpine
      - amazonlinux
      - archlinux
      - centos
      - debian
      - oraclelinux
      - photon
      - scientificlinux
      - ubuntu
      - shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Slack Post Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          include_jobs: true
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
