name: ci
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - "*.md"
  pull_request:
    branches:
      - master
      - main

jobs:
  create-matrices:
    name: Create version matrices
    runs-on: ubuntu-latest
    outputs:
      alpine-versions: ${{steps.versions.outputs.alpine-versions}}
      amazonlinux-versions: ${{steps.versions.outputs.amazonlinux-versions}}
      archlinux-versions: ${{steps.versions.outputs.archlinux-versions}}
      centos-versions: ${{steps.versions.outputs.centos-versions}}
      debian-versions: ${{steps.versions.outputs.debian-versions}}
      oraclelinux-versions: ${{steps.versions.outputs.oraclelinux-versions}}
      photon-versions: ${{steps.versions.outputs.photon-versions}}
      scientificlinux-versions: ${{steps.versions.outputs.scientificlinux-versions}}
      ubuntu-versions: ${{steps.versions.outputs.ubuntu-versions}}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Get version matrices
        id: versions
        uses: ./.github/workflows/composite/get-versions
  alpine:
    runs-on: ubuntu-latest
    needs: create-matrices
    strategy:
      fail-fast: false
      matrix:
        version: ${{fromJson(needs.create-matrices.outputs.alpine-versions)}}
    name: Build on Alpine Linux ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Generate Dockerfile for Alpine Linux ${{ matrix.version }}
        run: Dockerfiles/alpine/${{ matrix.version }}/manage.sh --generate
      - name: Run Hadolint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/hadolint/master/pipeline.sh)
      - name: Build on Alpine Linux ${{ matrix.version }}
        run: Dockerfiles/alpine/${{ matrix.version }}/manage.sh --build --clean
  amazonlinux:
    runs-on: ubuntu-latest
    needs: create-matrices
    strategy:
      fail-fast: false
      matrix:
        version: ${{fromJson(needs.create-matrices.outputs.amazonlinux-versions)}}
    name: Build on Amazon Linux ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Generate Dockerfile for Amazon Linux ${{ matrix.version }}
        run:  Dockerfiles/amazonlinux/${{ matrix.version }}/manage.sh --generate
      - name: Run Hadolint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/hadolint/master/pipeline.sh)
      - name: Build on Amazon Linux ${{ matrix.version }}
        run: Dockerfiles/amazonlinux/${{ matrix.version }}/manage.sh --build --clean
  archlinux:
    runs-on: ubuntu-latest
    needs: create-matrices
    strategy:
      fail-fast: false
      matrix:
        version: ${{fromJson(needs.create-matrices.outputs.archlinux-versions)}}
    name: Build on Arch Linux ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Generate Dockerfile for Arch Linux ${{ matrix.version }}
        run:  Dockerfiles/archlinux/${{ matrix.version }}/manage.sh --generate
      - name: Run Hadolint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/hadolint/master/pipeline.sh)
      - name: Build on Arch Linux ${{ matrix.version }}
        run: Dockerfiles/archlinux/${{ matrix.version }}/manage.sh --build --clean
  centos:
    runs-on: ubuntu-latest
    needs: create-matrices
    strategy:
      fail-fast: false
      matrix:
        version: ${{fromJson(needs.create-matrices.outputs.centos-versions)}}
    name: Build on Centos ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Generate Dockerfile for Centos ${{ matrix.version }}
        run: Dockerfiles/centos/${{ matrix.version }}/manage.sh --generate
      - name: Run Hadolint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/hadolint/master/pipeline.sh)
      - name: Build on Centos ${{ matrix.version }}
        run: Dockerfiles/centos/${{ matrix.version }}/manage.sh --build --clean
  debian:
    runs-on: ubuntu-latest
    needs: create-matrices
    strategy:
      fail-fast: false
      matrix:
        version: ${{fromJson(needs.create-matrices.outputs.debian-versions)}}
    name: Build on Debian ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Generate Dockerfile for Debian ${{ matrix.version }}
        run: Dockerfiles/debian/${{ matrix.version }}/manage.sh --generate
      - name: Run Hadolint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/hadolint/master/pipeline.sh)
      - name: Build on Debian ${{ matrix.version }}
        run: Dockerfiles/debian/${{ matrix.version }}/manage.sh --build --clean
  oraclelinux:
    runs-on: ubuntu-latest
    needs: create-matrices
    strategy:
      fail-fast: false
      matrix:
        version: ${{fromJson(needs.create-matrices.outputs.oraclelinux-versions)}}
    name: Build on Oracle Linux ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Generate Dockerfile for Oracle Linux ${{ matrix.version }}
        run: Dockerfiles/oraclelinux/${{ matrix.version }}/manage.sh --generate
      - name: Run Hadolint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/hadolint/master/pipeline.sh)
      - name: Build on Oracle Linux ${{ matrix.version }}
        run: Dockerfiles/oraclelinux/${{ matrix.version }}/manage.sh --build --clean
  photon:
    runs-on: ubuntu-latest
    needs: create-matrices
    strategy:
      fail-fast: false
      matrix:
        version: ${{fromJson(needs.create-matrices.outputs.photon-versions)}}
    name: Build on Photon ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Generate Dockerfile for Photon ${{ matrix.version }}
        run: Dockerfiles/photon/${{ matrix.version }}/manage.sh --generate
      - name: Run Hadolint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/hadolint/master/pipeline.sh)
      - name: Build on Photon ${{ matrix.version }}
        run: Dockerfiles/photon/${{ matrix.version }}/manage.sh --build --clean
  scientificlinux:
    runs-on: ubuntu-latest
    needs: create-matrices
    strategy:
      fail-fast: false
      matrix:
        version: ${{fromJson(needs.create-matrices.outputs.scientificlinux-versions)}}
    name: Build on Scientific Linux ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Generate Dockerfile for Scientific Linux ${{ matrix.version }}
        run: Dockerfiles/sl/${{ matrix.version }}/manage.sh --generate
      - name: Run Hadolint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/hadolint/master/pipeline.sh)
      - name: Build on Scientific Linux ${{ matrix.version }}
        run: Dockerfiles/sl/${{ matrix.version }}/manage.sh --build --clean
  ubuntu:
    runs-on: ubuntu-latest
    needs: create-matrices
    strategy:
      fail-fast: false
      matrix:
        version: ${{fromJson(needs.create-matrices.outputs.ubuntu-versions)}}
    name: Build on Ubuntu ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Generate Dockerfile for Ubuntu ${{ matrix.version }}
        run: Dockerfiles/ubuntu/${{ matrix.version }}/manage.sh --generate
      - name: Run Hadolint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/hadolint/master/pipeline.sh)
      - name: Build on Ubuntu ${{ matrix.version }}
        run: Dockerfiles/ubuntu/${{ matrix.version }}/manage.sh --build --clean
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Shellcheck
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/shellcheck/master/pipeline.sh)
  slack-workflow-status:
    if: always()
    name: Slack Post Workflow Notification
    needs:
      - shellcheck
      - alpine
      - amazonlinux
      - archlinux
      - centos
      - debian
      - oraclelinux
      - photon
      - scientificlinux
      - ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Slack Post Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          include_jobs: true
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
