name: ci
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - "*.md"
  pull_request:
    branches:
      - master

jobs:
  get-git-ref:
    name: Get Git Ref
    runs-on: ubuntu-latest
    outputs:
      ref: ${{steps.get-git-ref.outputs.ref}}
    steps:
      - name: Get Git Ref
        run: echo "::set-output name=ref::${{ github.ref }}"
  build:
    needs: get-git-ref
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        os-name: [ almalinux, alpine, amazonlinux, archlinux, centos, debian, oraclelinux, photon, rockylinux ]
    name: ${{ matrix.os-name }}
    steps:
      - name: Build Test
        uses: actionstoolbox/container-framework-actions/.github/workflows/multiple-os-workflow.yml@master
        with:
          directory: ${{ matrix.os-name }}
          ref: ${{ needs.get-git-ref.outputs.ref }}
  shellcheck:
    needs: get-git-ref
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.get-git-ref.outputs.ref }}
      - name: Run Shellcheck
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/shellcheck/master/pipeline.sh)
  yaml-lint:
    needs: get-git-ref
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.get-git-ref.outputs.ref }}
      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Run YAML-Lint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/yaml-lint/master/pipeline.sh)
  slack-message-finish:
    if: always()
    name: Slack Post Workflow Notification
    needs:
      - build
      - shellcheck
      - yaml-lint
    runs-on: ubuntu-latest
    steps:
      - name: Slack message
        uses: come25136/workflow-notification-for-slack@main
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          include_jobs: on-failure
