name: ci
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - "*.md"
  pull_request:
    branches:
      - master
      - main

jobs:
  alpine:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '3.11', '3.12', '3.13', '3.14', '3.15' ]
    name: Build on Alpine Linux ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Generate Dockerfile for Alpine Linux ${{ matrix.version }}
        run: Dockerfiles/alpine/${{ matrix.version }}/manage.sh --generate
      - name: Run Hadolint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/hadolint/master/pipeline.sh)
      - name: Build on Alpine Linux ${{ matrix.version }}
        run: Dockerfiles/alpine/${{ matrix.version }}/manage.sh --build --clean
  amazonlinux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '1', '2' ]
    name: Build on Amazon Linux ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Generate Dockerfile for Amazon Linux ${{ matrix.version }}
        run:  Dockerfiles/amazonlinux/${{ matrix.version }}/manage.sh --generate
      - name: Run Hadolint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/hadolint/master/pipeline.sh)
      - name: Build on Amazon Linux ${{ matrix.version }}
        run: Dockerfiles/amazonlinux/${{ matrix.version }}/manage.sh --build --clean
  archlinux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ 'base' ]
    name: Build on Arch Linux ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Generate Dockerfile for Arch Linux ${{ matrix.version }}
        run:  Dockerfiles/archlinux/${{ matrix.version }}/manage.sh --generate
      - name: Run Hadolint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/hadolint/master/pipeline.sh)
      - name: Build on Arch Linux ${{ matrix.version }}
        run: Dockerfiles/archlinux/${{ matrix.version }}/manage.sh --build --clean
  centos:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '7', '8' ]
    name: Build on Centos ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Generate Dockerfile for Centos ${{ matrix.version }}
        run: Dockerfiles/centos/${{ matrix.version }}/manage.sh --generate
      - name: Run Hadolint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/hadolint/master/pipeline.sh)
      - name: Build on Centos ${{ matrix.version }}
        run: Dockerfiles/centos/${{ matrix.version }}/manage.sh --build --clean
  debian:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '9', '9-slim', '10', '10-slim', '11', '11-slim', '12', '12-slim' ]
    name: Build on Debian ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Generate Dockerfile for Debian ${{ matrix.version }}
        run: Dockerfiles/debian/${{ matrix.version }}/manage.sh --generate
      - name: Run Hadolint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/hadolint/master/pipeline.sh)
      - name: Build on Debian ${{ matrix.version }}
        run: Dockerfiles/debian/${{ matrix.version }}/manage.sh --build --clean
  oraclelinux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '7', '7-slim', '8', '8-slim' ]
    name: Build on Oracle Linux ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Generate Dockerfile for Oracle Linux ${{ matrix.version }}
        run: Dockerfiles/oraclelinux/${{ matrix.version }}/manage.sh --generate
      - name: Run Hadolint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/hadolint/master/pipeline.sh)
      - name: Build on Oracle Linux ${{ matrix.version }}
        run: Dockerfiles/oraclelinux/${{ matrix.version }}/manage.sh --build --clean
  photon:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '1.0', '2.0', '3.0', '4.0' ]
    name: Build on Photon ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Generate Dockerfile for Photon ${{ matrix.version }}
        run: Dockerfiles/photon/${{ matrix.version }}/manage.sh --generate
      - name: Run Hadolint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/hadolint/master/pipeline.sh)
      - name: Build on Photon ${{ matrix.version }}
        run: Dockerfiles/photon/${{ matrix.version }}/manage.sh --build --clean
  sl:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '7' ]
    name: Build on Scientific Linux ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Generate Dockerfile for Scientific Linux ${{ matrix.version }}
        run: Dockerfiles/sl/${{ matrix.version }}/manage.sh --generate
      - name: Run Hadolint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/hadolint/master/pipeline.sh)
      - name: Build on Scientific Linux ${{ matrix.version }}
        run: Dockerfiles/sl/${{ matrix.version }}/manage.sh --build --clean
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '14.04', '16.04', '18.04', '20.04', '22.04' ]
    name: Build on Ubuntu ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Generate Dockerfile for Ubuntu ${{ matrix.version }}
        run: Dockerfiles/ubuntu/${{ matrix.version }}/manage.sh --generate
      - name: Run Hadolint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/hadolint/master/pipeline.sh)
      - name: Build on Ubuntu ${{ matrix.version }}
        run: Dockerfiles/ubuntu/${{ matrix.version }}/manage.sh --build --clean
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Shellcheck
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/shellcheck/master/pipeline.sh)
  slack-workflow-status:
    if: always()
    name: Slack Post Workflow Notification
    needs:
      - alpine
      - amazonlinux
      - archlinux
      - centos
      - debian
      - oraclelinux
      - photon
      - sl
      - ubuntu
      - shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Slack Post Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          include_jobs: true
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
