name: ci
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - "*.md"
  pull_request:
    branches:
      - master
      - main

jobs:
  get-git-ref:
    name: Get Git Ref
    runs-on: ubuntu-latest
    outputs:
      ref: ${{steps.get-git-ref.outputs.ref}}
    steps:
      - name: Get Git Ref
        run: echo "::set-output name=ref::${{ github.ref }}"
  list-changes:
    needs: get-git-ref
    name: List Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.get-git-ref.outputs.ref }}
      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v18.5
      - name: List all added files
        run: |
          for file in ${{ steps.changed-files.outputs.modified_files }}; do
            echo "$file was added"
          done
  almalinux:
    needs: get-git-ref
    name: Alma Linux
    uses: actionstoolbox/container-framework-actions/.github/workflows/multiple-os-workflow.yml@master
    with:
      directory: almalinux
      ref: ${{ needs.get-git-ref.outputs.ref }}
      max-parallel: 2
  slack-message-finish:
    if: always()
    name: Slack Post Workflow Notification
    needs:
      - list-changes
      - almalinux
   runs-on: ubuntu-latest
    steps:
      - name: Slack message
        uses: come25136/workflow-notification-for-slack@main
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          include_jobs: on-failure
