name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install Ruby dependencies
#        run: bundle update --bundler && bundle install
        run: bundle install
      - name: Run script
        run: bashcov manage-all.sh
      - name: Upload reports to Codecov
        run: bash <(curl -s https://codecov.io/bash) -t ${{secrets.CODECOV_TOKEN}}
