name: test
on: push

jobs:
 get-git-ref:
    name: Get Git Ref
    runs-on: ubuntu-latest
    outputs:
      ref: ${{steps.get-git-ref.outputs.ref}}
    steps:
      - name: Get Git Ref
        run: echo "::set-output name=ref::${{ github.ref }}"
  example_matrix:
    needs: get-git-ref
    strategy:
      matrix:
#        os: [almalinux, alpine, amazonlinux, archlinux, centos, debian, oraclelinux, photon, rockylinux, scientificlinux, ubuntu]
        os: [almalinux]
        include:
          - os: almalinux
            full-name: Alma Linux
            directory: almalinux
            max-parallel: 2
    steps:
    - name: ${{ matrix.full-name }}
#      if: contains(needs.changed-files.outputs.all_modified_files, 'Dockerfiles/almalinux/')
      uses: actionstoolbox/container-framework-actions/.github/workflows/multiple-os-workflow.yml@master
      with:
        directory: ${{ matrix.directory }}
        ref: ${{ needs.get-git-ref.outputs.ref }}
        max-parallel: ${{ matrix.max-parallel }}
